# Deploy configuration file
# -------------------------
# check_interval: check interval in seconds
# time_between_servers: time between deployment on multiple servers in seconds
# initial_nr_commits: the number of commits saved to database of a new project

api:
  url: http://marijn.mono.sdn.io/deployapi
#  url: http://localhost:6127

repositories:
  path: /var/www/deploy/repositories
  check_interval: 60
  initial_nr_commits: 20

queue:
  check_interval: 30

build:
  path: /var/www/deploy/build
  environment: export MONO_IOMAP=all; export EnableNuGetPackageRestore=true; export LD_LIBRARY_PATH=/opt/mono-master/lib:$LD_LIBRARY_PATH; export PKG_CONFIG_PATH=/opt/mono-master/lib/pkgconfig:$PKG_CONFIG_PATH;
  command: xbuild /verbosity:detailed /p:Configuration=Release /p:OutputPath={builddirectory}/bin /fl /flp:LogFile={builddirectory}/build.log /tv:4.0 {projectfile} > /dev/null

deploy:
  time_between_servers: 15