api:
  url: http://marijn.mono.sdn.io/deployapi
#  url: http://localhost:6127

repositories:
  path: /var/www/deploy
  check_interval: 1
  initial_nr_commits: 20

queue:
  check_interval: 5

deploy:
  time_between_servers: 15